[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
cached = "0.26.2"
js-sys = "0.3.22"
wasm-bindgen = "0.2.63"
console_error_panic_hook = "0.1.6"
wee_alloc = { version = "0.4.5", optional = true }
